pipeline {
    agent any //burada herhangi bir ajan kullanabiliriz

    environment {
        DOCKER_REGISTRY = 'registry'
        IMAGE_NAME = 'springboot-hello-world'
        KUBECONFIG_ID = 'kubeconfig-credentials-id' //burası jenkins için kubeconfig kimlik bilgisi idsi
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Maven') {
            steps {
                sh './mvnw clean package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("${DOCKER_REGISTRY}/${IMAGE_NAME}:${env.BUILD_NUMBER}") //
                }
            }
        }

	        stage('Push Docker Image') {
	            steps {
	                script {
	                    def registryUrl = DOCKER_REGISTRY
	                    if (!registryUrl.startsWith('http://') && !registryUrl.startsWith('https://')) {
	                        registryUrl = "https://${registryUrl}"
	                    }
	                    docker.withRegistry(registryUrl, 'docker-hub-credentials') {
	                        dockerImage.push()
	                        dockerImage.push('latest')
	                    }
	                }
	            }
	        }

        stage('Deploy to K8s with Helm') {
            steps {
                withKubeConfig([credentialsId: "${KUBECONFIG_ID}"]) {
                    dir('DevOpsSolution') {
                        sh """
                        helm upgrade --install springboot-hello-world ./springboot-hello-world-chart \
                        --set image.tag=${env.BUILD_NUMBER} \
                        --namespace default
                        """
                    }
                }
            }
        }
    }
}
